### PR TITLE
No longer export the internal methods from SQLite3

### PR DESCRIPTION
**Pull request by Dretch**

### CODE REVIEW

**Comment by justinwoo** [comment]
I guess this is fine, but do you mind moving them to an internal module?

**Comment by Dretch** [comment]
As you desire (well, perhaps!).

My original motivation was to make the docs easier to read by removing the internal functions. Both using an Internal module and just not-exporting the internal functions will achieve that.

**Comment by justinwoo** [comment]
Thanks!

**Comment by justinwoo** [comment]
Published here: https://pursuit.purescript.org/packages/purescript-node-sqlite3/4.0.0

**Pull request merged**
